/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "/cycle": "/轮",
    ". Check it out!": "． 点击这里查看详情！",
    "- space is dangerous!": "- 太空很危险!",
    ",\n                        you": ",\n                        你",
    "You are facing an immense, dark mass of writhing tentacles, teeth and eyes that are fixated on the station.": "你面对的是一大堆巨大的、黑暗的、扭动着的触须、牙齿和眼睛，它们都盯着空间站。",
    "You defeated": "你被击败了",
    "You have already played": "你已经玩过了",
    "You managed to blast through": "你成功通过了",
    "you will collect.": "你会收集。",
    "Your damage output is multiplied by your": "你的伤害输出乘以你的",
    "Xp/Cycle": "经验值/轮",
    "Xp left": "经验剩余",
    "Station Name": "站点名称",
    "Strength:": "力量:",
    "Steel": "钢",
    "Team": "团队",
    "Tiny Toolbox": "小工具箱",
    "Total grid load:": "电网总负荷:",
    "Value": "价值",
    "Welcome to Progress Station": "欢迎来到进度站",
    "Wilson Page": "威尔逊页面",
    "win you the game": "赢得你的游戏",
    "Through the glazed front you see not only large parts of the station\n                    as they drift away destroyed through space, but also a many-limbed,\n                    dark mass that disappears silently into the vastness of space.\n                    At least for now.": "透过玻璃幕墙，你不仅可以看到空间站的大部分在太空中被摧毁，还可以看到一个多肢的黑暗物体，无声地消失在浩瀚的太空中。\n至少现在是这样。",
    "The vacuum of space around your station suppresses all noise, but you can feel the hatred of\n                    the alien beast and see it's determination to destroy everything you have built up.": "空间站周围的真空空间压制了所有的噪音，但你可以感受到外星野兽\n的仇恨，看到它摧毁你所建立的一切的决心。",
    "The universe is safe, and it feels as if a curse was lifted of your soul.": "宇宙是安全的，感觉好像你灵魂的诅咒被解除了。",
    "A name flashes on the main console:": "一个名字在主控制台上闪烁:",
    "You awake on a dimly lit, emergency-powered bridge of what appears\n                    to be a heavily damaged space station.": "你在一个灯光昏暗、紧急供电的桥上醒来，桥上似乎是一个严重受损的空间站。",
    "Reset": "重置",
    "Reset game": "重置游戏",
    "Void Vikings": "虚空维京人",
    "Space Pirates": "海盗",
    "Safe Zone": "安全区",
    "Scavengers": "拾荒者",
    "Sci-fi mode": "科幻模式",
    "Reduces": "减少",
    "Re-roll": "重选",
    "Research": "研究",
    "Take control": "开始控制",
    "Re-roll name": "重选名称",
    "Rapid Rumble Tower": "急速隆隆塔",
    "Comet Crawlers": "彗星爬行者",
    "reaches": "达到",
    "Rescue Capsule": "救生舱",
    "More": "更多",
    "Off": "关闭",
    "On": "打开",
    "Protection": "保护",
    "Progress Station": "进度站",
    "Progress Knight": "骑士进度条",
    "Products": "产品",
    "Prepare!": "准备好了！",
    "Population": "人口",
    "Max level of modules = sum of that module's operations max level.": "模块的最大等级 = 该模块的操作的最大等级之和。",
    "Location": "位置",
    "Load:": "负载:",
    "levels of defense.": "防御等级。",
    "Level:": "等级:",
    "Level": "等级",
    "level": "等级",
    "Light/dark mode": "浅色/深色 模式",
    "Mark": "标记",
    "Military": "军事",
    "Mining Bay": "采矿湾",
    "Modifier": "词缀",
    "Modules": "模块",
    "Growth": "成长",
    "Open": "打开",
    "Not yet": "暂未",
    "Once your": "一旦你的",
    "Next unlock at:": "下一个解锁：",
    "Natanael Gama": "纳撒内尔·伽马",
    "Keep save": "保留存档",
    "Initial Vision": "初始视觉",
    "in the past, thank you!": "在过去，谢谢你!",
    "Heavy Glitz": "重磅浮华",
    "Grid Load": "电网负载",
    "Grid": "电网",
    "Hard reset game": "硬重置游戏",
    "Grid Strength": "电网强度",
    "Guile is Strength": "诡计就是力量",
    "Fuel": "燃料",
    "Fonts": "字体",
    "from Boss": "来自 Boss",
    "Furnace Module": "熔炉模块",
    "Defensive Module": "防御模块",
    "Fusion Powered Thunder Dragon": "聚变动力雷龙",
    "HP left": "生命值剩余",
    "Dmg": "伤害",
    "Doctrine": "信条",
    "Essence of Unknown": "未知精华",
    "Everyone Matters": "每个人都很重要",
    "Laser Turrets": "激光炮塔",
    "levels": "等级",
    "level ": "等级 ",
    "Light": "浅色",
    "Limits the number of concurrently active operations.": "限制并发活动操作的数量。",
    "Astral Sharks": "星体鲨鱼",
    "Max Level:": "最高等级：",
    "Mechano Maker": "机械制造商",
    "Mined Resource": "开采的资源",
    "Orbiting Oasis": "轨道绿洲",
    "Our recommendation is to start with a fresh game. But you can also try and let the game reuse your save file.": "我们建议你从一款全新的游戏开始。但是你也可以试着让游戏重用你的保存文件。",
    "Overcoming the last level of the boss will": "击败Boss的最后一关",
    "On the main console you see what appears to be an ancient video game:": "在主控制台上，你看到的似乎是一个古老的电子游戏:",
    "Sensors are going wild, the proximity alert shrieks and the light of stars\n                    gets swallowed by an unidentifiable mass.": "传感器开始失控，接近警报发出尖叫声，恒星的光被一团无法辨认的物质吞噬。",
    "The game has evolved a lot since then and we can not guarantee that your save game is still fully compatible.": "从那时起，游戏已经发展了很多，我们不能保证你保存的游戏仍然完全兼容。",
    "The more levels of the boss that you overcome, the more": "你克服的Boss关卡越多，你就会获得更多",
    "The ole reliable of power sources. It may grumble and spew smoke, but it'll keep the lights on when all else fails.": "可靠的电源。它可能会发牢骚，冒烟，但当其他一切都失败时，它会保持亮灯。",
    "Unravel a Galactic Secret by long pressing its progress bar.": "通过长按进度条揭开银河秘密",
    "With the last of your strength, you save yourself in the rescue capsule.": "用你最后的力气，你在救生舱里自救。",
    "Everything was going great on your space station, but suddenly your\n                    heart sinks into your stomach, and you get that same feeling as when\n                    you came to your senses alone on this very station.": "在你的空间站上，一切都很顺利，但突然你的心沉到了胃里，你得到的感觉和你在这个空间站上独自恢复理智时一样。",
    "In the next play-through, you will progress much faster.": "在接下来的游戏中，你的进度会更快。",
    "is disregarded.\nThe total can never be less than": "被忽视了。\n总数永远不能少于",
    "Experimental": "实验性",
    "exceeding": "超过",
    "lvl": "等级",
    "Heat": "热量",
    "Import/export save": "导入/导出 存档",
    "Increases": "增加",
    "increases": "增加",
    "Industry": "工业",
    "Keep playing": "继续游戏",
    "lose the battle": "输掉战斗",
    "Lost Scavengers": "迷失的拾荒者",
    "Energy": "能源",
    "Drill": "钻机",
    "s power is overwhelming and annihilates your crew, your station, everything.": "的力量是压倒性的，它会消灭你的船员，你的空间站，你的一切。",
    "s near endless defenses.": "接近无穷无尽的防御。",
    "3rd Party Assets": "第三方素材",
    "4D\xa0Printer": "4D打印机",
    "Active": "激活",
    "A game by": "作者 ",
    "A Million Meteor Maws": "一百万颗流星",
    "Affects all progress speed.": "影响所有的进度速度。",
    "Amount of": "数量关于",
    "and is directly damaging your": "并直接损害你的",
    "and increases damage in Battles.": "并增加战斗中的伤害。",
    "and the progress speed from": "和进度速度从",
    "Anti-Matter Thunder Dragon": "反物质雷龙",
    "Anti-Missile Swarm": "反导蜂群",
    "Apex Astral Sharks": "尖星鲨",
    "Apocalyptic Astrogoblins": "天启星哥布林",
    "Attribute": "属性",
    "Attributes": "属性",
    "Background": "背景",
    "Base": "基础",
    "Battle": "战斗",
    "battles or": "战斗或",
    "Belongs to": "属于",
    "Black Hole Space Pirates": "黑洞太空海盗",
    "Blinding Nova Flies": "致盲新星苍蝇",
    "Bold Astrogoblins": "大胆的星哥布林",
    "Bullet Sponge": "子弹海绵",
    "Captain's Quarter": "船长宿舍",
    "Celestial Thunder Dragon": "天体雷龙",
    "Rescue Capsule": "",
    "Sector": "扇区",
    "Simple Color": "简约色彩",
    "Space Rocks": "太空岩石",
    "Plastics": "塑料",
    "Point of Interest": "兴趣点",
    "Pause": "暂停",
    "Stray Nova Flies": "流浪新星苍蝇",
    "Sublime Thunder Dragon": "超绝雷龙",
    "Station Core": "空间站核心",
    "Start new game": "开始新游戏",
    "Asteroid Haven III": "小行星避难所 III",
    "per cycle": "每轮",
    "Ravaging Comet Crawlers": "肆虐的彗星爬行者",
    "Pick up survivors": "救起幸存者",
    "Keep off": "保持关闭",
    "Support": "支持",
    "Turn on!": "打开!",
    "United For Victory": "团结一致争取胜利",
    "General": "常规",
    "Gliding Star Mantas": "滑翔星蝠鲼",
    "Lenard": "勒纳",
    "Not enough Grid Strength!": "电网强度不够！",
    "Breakdown": "故障",
    "Check out the original game that Progress Station is based upon.": "看看Progress Station基于的原版游戏。",
    "Credits": "鸣谢",
    "Crew Expansion": "船员扩展",
    "currently.": "当前。",
    "Danger": "危险",
    "Date:": "日期:",
    "Blisscandy Icon III": "极乐圣地图标 III",
    "Careful now!": "现在小心点！",
    "Decrepit Thunder Dragon": "老旧的雷龙",
    "Dev Ops": "开发运维",
    "Duper Void Vikings": "愚蠢的虚空维京人",
    "Diesel": "柴油",
    "Feature Coder": "功能编码员",
    "Fearless Astrogoblins": "无所畏惧的星哥布林",
    "Star Mantas": "明星蝠鲼",
    "Standby\xa0Generator": "备用发电机",
    "Dark Galaxy Scavengers": "黑暗星系清道夫",
    "The boss has": "Boss",
    "This browser game offers sound!": "这个网页游戏提供声音！",
    "Typori": "泰波里",
    "Trailer Production": "拖车生产",
    "Traced Star Mantas": "追踪星蝠鲼",
    "Unbeatable Scavengers": "",
    "Snorgolan, Eternal Essence Harvester": "史诺戈兰，永恒精华收集者",
    "Snorgolan, Eternal Essence Harvester": "史诺戈兰，永恒精华收集者",
    "Audio Designer & Game Balance Designer": "音频设计师和游戏平衡设计师",
    "attacks you": "攻击了你",
    "Fight!": "战斗!",
    "Feral Astrogoblins": "野生星哥布林",
    "Congratulations!": "恭喜!",
    "Cosmic's Edge Space Pirates": "宇宙边缘的太空海盗",
    "Cosmos' Dread Space Pirates": "宇宙的恐怖太空海盗",
    "Clew of Meteor Maws": "流星之爪的线索",
    "Cruising Space Pirates": "巡航太空海盗",
    "Crystal Gardens": "水晶花园",
    "Curious Star Mantas": "好奇的星蝠鲼",
    "currently assigned.": "当前已分配。",
    "Sound": "声音",
    "source": "源码",
    "Space": "太空",
    "Super Nova Flies": "超级新星苍蝇",
    "The Big Spinny": "大纺锤",
    "After unraveling a Secret, the cost per Secret will increase": "在解开一个秘密后，每个秘密的成本将会增加",
    "Aggressive Comet Crawlers": "咄咄逼人的彗星爬行者",
    "Faster than Light Astral Sharks": "比光星鲨还快",
    "Fade to black": "逐渐变黑",
    "Garbage": "垃圾",
    "Two more Meteor Maws": "",
    "Vision Keeper & Visual Coder": "视觉管理员和视觉编码员",
    "Universe-Raiding Void Vikings": "扫荡宇宙的虚空维京人",
    "Lone Astral Sharks": "孤星鲨鱼",
    "Crystal Gardens": "水晶花园",
    "As the game is currently in beta and we pushed a big update, \n                            the save game structure has changed.": "由于游戏目前处于测试阶段，我们推出了一个大的更新，所以保存游戏的结构发生了变化。",
    "You might see a missing unlock or two, but should easily be able to unlock those again.": "你可能会看到一个或两个丢失的解锁，但应该能够轻松地再次解锁。",
    "You might lose a lot of population.": "你可能会失去很多人口。",
    "Wimpy Astrogoblins": "懦弱的星哥布林",
    "If you don't want to risk it, feel free to start fresh.": "如果你不想冒险，可以重新开始。",
    "Laser Turrets": "激光炮塔",
    "Legendary Astrogoblins": "传说星哥布林",
    "United For Victory": "团结争取胜利",
    "Unbeatable Scavengers": "无敌的拾荒者",
    "⚠️ Warning": "⚠️ 警告",
    "A Million Meteor Maws": "一百万颗流星",
    "All systems nominal.": "所有系统正常运行。",
    "Unlocks new knowledge.": "解锁新知识。",
    "Unstable Save Game found": "发现不稳定的游戏存档",
    "Station\xa0Core": "站点核心",
    "Station Dmg": "站点伤害",
    "Enabling these will reduce the game's performance!": "启用这些会降低游戏的性能！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "VFX": "视觉效果",
    "Kringel Games": "Kringel Games",
    "Janik": "Janik",
    "Gamma Sector": "伽马扇区",
    "Beta Sector": "贝塔扇区",
    "Delta Sector": "德尔塔扇区",
    "Alpha Sector": "阿尔法扇区",
    "Lodash": "Lodash",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    "(": "(",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "(Defeated ": "(击败了 ",
    "(Point of Interest: ": "(兴趣点：",
    "Wimpy Astrogoblins": "懦弱的星哥布林",
    "Two Meteor Maws": "两个流星肚",
    "Reveling ": "狂欢的",
    "Duper ": "愚蠢的",
    "Ruthless ": "无情的",
    "Super ": "超级",
    "Roaming ": "漫游太空的",
    "Ravaging ": "肆虐的",
    "Lone ": "孤独的",
    "Point of Interest: ": "兴趣点:",
    "Fighting ": "攻击",
    "Defeated ": "击败了",
    "Defensive Module: Protection: ": "防御模块: 保护: ",
    "Defensive Module: Turrets: ": "防御模块: 炮塔: ",
    "Furnace Module: Products: ": "熔炉模块: 产品: ",
    "Furnace Module: Fuel: ": "熔炉模块: 燃料: ",
    "Mining Bay: Drill: ": "采矿湾: 钻机: ",
    "Mining Bay: Mined Resource: ": "采矿湾: 开采的资源: ",
    "Captain's Quarter: Tiny Toolbox: ": "船长宿舍: 小工具箱: ",
    "Required: ": "要求: ",
    "Stray ": "流浪的",
    "Quarters Module: Crew Expansion: ": "宿舍模块：船员扩展：",
    "Quarters Module: Doctrine: ": "宿舍模块：信条：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ")": ")",
    "and thus directly damaging your": "从而直接损害你的",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^\+(.+) Military\nx(.+) Industry\nx(.+) Energy$/, '\+$1 军事\nx$2 工业\nx$3 能源'],
    [/^\+(.+) Industry\nx(.+) Military$/, '\+$1 工业\nx$2 军事'],
    [/^\+(.+) Research\nx(.+) Military$/, '\+$1 研究\nx$2 军事'],
    [/^\+(.+) Energy\nx(.+) Military$/, '\+$1 能源\nx$2 军事'],
    [/^\+(.+) Energy\nx(.+) Industry$/, '\+$1 能源\nx$2 工业'],
    [/^\+(.+) Growth\nx(.+) Military$/, '\+$1 成长\nx$2 军事'],
    [/^\+(.+) Growth\nx(.+) Industry$/, '\+$1 成长\nx$2 工业'],
    [/^\+(.+) Military\nx(.+) Military$/, '\+$1 军事\nx$2 军事'],
    [/^\+(.+) Military\nx(.+) Industry$/, '\+$1 军事\nx$2 工业'],
    [/^\+(.+) Heat\nx(.+) Growth$/, '\+$1 热量\nx$2 成长'],
    [/^\+(.+) Military\nx(.+) Growth$/, '\+$1 军事\nx$2 成长'],
    [/^x(.+) Growth\nx(.+) Industry\nx(.+) Energy$/, 'x$1 成长\nx$2 工业\nx$3 能源'],
    [/^x(.+) Industry\nx(.+) Research$/, 'x$1 工业\nx$2 研究'],
    [/^x([\d\.]+) Military$/, 'x$1 军事'],
    [/^x([\d\.]+) Industry$/, 'x$1 工业'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) Energy$/, '\+$1 能源'],
    [/^\+([\d\.]+) Industry$/, '\+$1 工业'],
    [/^\+([\d\.]+) Military$/, '\+$1 军事'],
    [/^\+([\d\.]+) Growth$/, '\+$1 成长'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);